import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowDown, ArrowLeft, ArrowUp, Brain, Download, Pencil, Plus, Save, Search, ShieldCheck, Trash2 } from "lucide-react";
import { api, download } from "../lib/api";
import { useApi, useDebounced } from "../lib/hooks";
import { cellText } from "../lib/format";
import { Badge, Button, Card, ConfirmDialog, Empty, ErrorBox, Field, Input, Loading, Modal, Notice, PageHeader, Pagination, Select, Tabs, cx, useToast } from "../components/ui";

type Tab = "rows" | "mapping" | "quality" | "profile" | "template";

export default function TableView() {
  const { id } = useParams();
  const { data: t, error, loading, reload } = useApi<any>(`/api/tables/${id}`);
  const [tab, setTab] = useState<Tab>("rows");
  const [rowFilter, setRowFilter] = useState<number[] | null>(null);
  useEffect(() => { if (t?.kind === "form") setTab("template"); }, [t?.kind]);

  if (loading && !t) return <Loading />;
  if (error) return <ErrorBox message={error} />;
  if (!t) return null;
  const tabs = t.kind === "form"
    ? [{ key: "template" as Tab, label: "Template" }]
    : [{ key: "rows" as Tab, label: `Rows (${t.rows.toLocaleString()})` }, { key: "mapping" as Tab, label: "Column mapping" },
      { key: "quality" as Tab, label: <span>Data quality {t.quality && <span className="ml-1 tabular text-muted">{t.quality.score}</span>}</span> }, { key: "profile" as Tab, label: "Engine profile (JSON)" }];
  return (
    <>
      <PageHeader back={<Link to="/data" className="mb-1 inline-flex items-center gap-1 text-[13px] text-muted hover:text-ink"><ArrowLeft className="size-3.5" /> Data Sheets</Link>}
        title={t.title} subtitle={<>{t.file} › {t.sheet} · range {t.range}{t.kind === "table" && <> · header row {t.header_row}</>}</>}
        actions={t.kind === "table" && <>
          <Button icon={<Download className="size-4" />} onClick={() => download(`/api/tables/${t.id}/export?format=xlsx`, `${t.sheet}.xlsx`)}>Excel</Button>
          <Button icon={<Download className="size-4" />} onClick={() => download(`/api/tables/${t.id}/export?format=csv`, `${t.sheet}.csv`)}>CSV</Button></>} />
      <Tabs tabs={tabs} value={tab} onChange={setTab} />
      {tab === "rows" && <RowsGrid t={t} rowFilter={rowFilter} clearFilter={() => setRowFilter(null)} />}
      {tab === "mapping" && <Mapping t={t} onSaved={() => reload(true)} />}
      {tab === "quality" && <Quality t={t} onShowRows={(rows) => { setRowFilter(rows); setTab("rows"); }} />}
      {tab === "profile" && <Card title="Engine profile" subtitle="The JSON configuration generated by the data-intelligence engine for this table. Stages and completion rules are evaluated from this - edit the mapping tab to change it.">
        <pre className="max-h-[70vh] overflow-auto rounded-lg bg-surface-2 p-4 text-[12px] leading-5">{JSON.stringify(t.profile, null, 2)}</pre></Card>}
      {tab === "template" && <Template t={t} />}
    </>
  );
}

// ------------------------------------------------------------------ rows
function RowsGrid({ t, rowFilter, clearFilter }: { t: any; rowFilter: number[] | null; clearFilter: () => void }) {
  const toast = useToast();
  const [q, setQ] = useState("");
  const dq = useDebounced(q, 300);
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState<{ col: string; dir: "asc" | "desc" } | null>(null);
  const [edit, setEdit] = useState<any | null>(null);
  const [del, setDel] = useState<any | null>(null);
  useEffect(() => setPage(1), [dq, rowFilter, sort]);
  const qs = new URLSearchParams({ page: String(page), size: "50" });
  if (dq) qs.set("q", dq);
  if (sort) { qs.set("sort", sort.col); qs.set("dir", sort.dir); }
  if (rowFilter) qs.set("rows", rowFilter.join(","));
  const { data, loading, error, reload } = useApi<any>(`/api/tables/${t.id}/rows?${qs}`);
  const roleOf = useMemo(() => Object.fromEntries(Object.entries(t.profile?.fields || {}).map(([r, c]) => [c, r])), [t]);
  const cols = t.columns as any[];

  const remove = async () => {
    try { await api(`/api/tables/${t.id}/rows/${del.id}`, { method: "DELETE" }); toast("Row deleted"); setDel(null); reload(true); }
    catch (e: any) { toast(e.message, "critical"); }
  };

  return (
    <Card bodyClass="p-0">
      <div className="flex flex-wrap items-center gap-2 border-b border-line p-3">
        <div className="relative min-w-[220px] flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted" />
          <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search all columns…" className="pl-9" /></div>
        {rowFilter && <Badge tone="warning">Showing {rowFilter.length} flagged rows <button className="ml-1 underline" onClick={clearFilter}>clear</button></Badge>}
        <Button variant="primary" icon={<Plus className="size-4" />} onClick={() => setEdit({})}>Add row</Button>
      </div>
      {error && <div className="p-4"><ErrorBox message={error} /></div>}
      {loading && !data ? <Loading /> : data && (data.rows.length === 0 ? <Empty title="No rows" /> : (
        <>
          <div className="max-h-[66vh] overflow-auto">
            <table className="w-full text-[12.5px]">
              <thead className="sticky top-0 z-10 bg-surface-2 text-left text-[12px] text-muted">
                <tr>
                  <th className="sticky left-0 bg-surface-2 px-3 py-2 font-medium">Row</th>
                  {cols.map((c) => (
                    <th key={c.name} className="whitespace-nowrap px-3 py-2 font-medium">
                      <button className="inline-flex items-center gap-1 hover:text-ink" onClick={() => setSort((s) => ({ col: c.name, dir: s?.col === c.name && s?.dir === "asc" ? "desc" : "asc" }))}>
                        {c.name}{sort?.col === c.name && (sort?.dir === "asc" ? <ArrowUp className="size-3" /> : <ArrowDown className="size-3" />)}
                      </button>
                      {roleOf[c.name] && <div className="text-[10.5px] font-normal text-primary">{roleOf[c.name].replace(/_/g, " ")}</div>}
                    </th>))}
                  <th className="px-3" />
                </tr>
              </thead>
              <tbody className={cx(loading && "opacity-60")}>
                {data.rows.map((r: any) => (
                  <tr key={r.id} className="group border-t border-line hover:bg-surface-2">
                    <td className="sticky left-0 bg-surface px-3 py-1.5 text-muted tabular group-hover:bg-surface-2">{r.row_no || "new"}</td>
                    {cols.map((c) => <td key={c.name} className={cx("max-w-[260px] truncate whitespace-nowrap px-3 py-1.5", ["integer", "number"].includes(c.dtype) && "text-right tabular")} title={cellText(r.data[c.name])}>{cellText(r.data[c.name])}</td>)}
                    <td className="whitespace-nowrap px-3 text-right opacity-0 group-hover:opacity-100 focus-within:opacity-100">
                      <button className="rounded p-1 text-muted hover:text-primary" aria-label="Edit row" onClick={() => setEdit(r)}><Pencil className="size-3.5" /></button>
                      <button className="rounded p-1 text-muted hover:text-critical" aria-label="Delete row" onClick={() => setDel(r)}><Trash2 className="size-3.5" /></button>
                    </td>
                  </tr>))}
              </tbody>
            </table>
          </div>
          <Pagination page={page} size={50} total={data.total} onPage={setPage} />
        </>))}
      <RowEditor t={t} row={edit} onClose={() => setEdit(null)} onSaved={() => { setEdit(null); reload(true); }} />
      <ConfirmDialog open={!!del} onClose={() => setDel(null)} onConfirm={remove} danger confirmLabel="Delete row" title="Delete this row?"
        message={`Row ${del?.row_no || ""} will be removed from the app's copy of this table. The original uploaded file is not changed.`} />
    </Card>
  );
}

function RowEditor({ t, row, onClose, onSaved }: { t: any; row: any | null; onClose: () => void; onSaved: () => void }) {
  const toast = useToast();
  const [vals, setVals] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  useEffect(() => {
    if (row) { setVals(Object.fromEntries(t.columns.map((c: any) => [c.name, cellText(row.data?.[c.name])]))); setErr(null); }
  }, [row, t.columns]);
  if (!row) return null;
  const isNew = !row.id;
  const save = async () => {
    setBusy(true);
    setErr(null);
    try {
      const data = isNew ? Object.fromEntries(Object.entries(vals).filter(([, v]) => v !== ""))
        : Object.fromEntries(Object.entries(vals).filter(([k, v]) => v !== cellText(row.data[k])).map(([k, v]) => [k, v === "" ? null : v]));
      await api(isNew ? `/api/tables/${t.id}/rows` : `/api/tables/${t.id}/rows/${row.id}`, { method: isNew ? "POST" : "PUT", json: { data } });
      toast(isNew ? "Row added" : "Row updated");
      onSaved();
    } catch (e: any) { setErr(e.message); } finally { setBusy(false); }
  };
  return (
    <Modal open onClose={onClose} title={isNew ? "Add row" : `Edit row ${row.row_no || ""}`} width="max-w-3xl"
      footer={<><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="primary" loading={busy} icon={<Save className="size-4" />} onClick={save}>Save</Button></>}>
      {err && <div className="mb-3"><ErrorBox message={err} /></div>}
      <div className="grid max-h-[60vh] gap-3 overflow-y-auto pr-1 sm:grid-cols-2 lg:grid-cols-3">
        {t.columns.map((c: any) => (
          <Field key={c.name} label={c.name}>
            <Input type={c.dtype === "date" ? "date" : c.dtype === "integer" || c.dtype === "number" ? "number" : "text"} step="any"
              value={vals[c.name] ?? ""} onChange={(e) => setVals((v) => ({ ...v, [c.name]: e.target.value }))} />
          </Field>))}
      </div>
    </Modal>
  );
}

// ------------------------------------------------------------------ mapping editor
function Mapping({ t, onSaved }: { t: any; onSaved: () => void }) {
  const toast = useToast();
  const { data: onto } = useApi<any>("/api/ontology");
  const [type, setType] = useState(t.role);
  const [map, setMap] = useState<Record<string, string>>(() => Object.fromEntries(Object.entries(t.profile?.fields || {}).map(([r, c]) => [c as string, r])));
  const [busy, setBusy] = useState(false);
  const colInfo = useMemo(() => Object.fromEntries((t.profile?.columns || []).map((c: any) => [c.column, c])), [t]);
  const dup = Object.values(map).filter((r, i, a) => r && a.indexOf(r) !== i && !["remarks", "address"].includes(r));

  const save = async () => {
    setBusy(true);
    try {
      const fields: Record<string, string> = {};
      for (const [col, role] of Object.entries(map)) if (role && !fields[role]) fields[role] = col;
      await api(`/api/tables/${t.id}/profile`, { method: "PUT", json: { table_type: type, fields } });
      toast("Mapping saved. The classifier is learning from your corrections.");
      onSaved();
    } catch (e: any) { toast(e.message, "critical"); } finally { setBusy(false); }
  };
  if (!onto) return <Loading />;
  return (
    <div className="space-y-4">
      <Notice>The neural classifier proposed these meanings from each column's header <i>and</i> its values. Correct anything that is wrong and save - every correction becomes training data, so the next upload of a similar sheet is recognised correctly.</Notice>
      <Card title="Table type" subtitle={`Detected: ${t.profile?.type_label ?? t.role} (${Math.round((t.profile?.type_confidence ?? t.confidence) * 100)}% confidence)`}
        actions={<Button variant="primary" loading={busy} disabled={dup.length > 0} icon={<Save className="size-4" />} onClick={save}>Save mapping</Button>}>
        <Select value={type} onChange={(e) => setType(e.target.value)} className="w-72">
          {onto.table_types.map((tt: any) => <option key={tt.key} value={tt.key}>{tt.label}</option>)}
        </Select>
        {dup.length > 0 && <p className="mt-2 text-[13px] text-critical">Each meaning can be used on one column only: {[...new Set(dup)].join(", ")}</p>}
      </Card>
      <Card bodyClass="p-0">
        <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-[13px]">
          <thead className="bg-surface-2 text-left text-[12px] text-muted"><tr><th className="px-5 py-2.5">Column</th><th className="px-3">Type</th><th className="px-3">Sample values</th><th className="px-3">Meaning</th><th className="px-5">Model confidence / alternatives</th></tr></thead>
          <tbody>{t.columns.map((c: any) => {
            const info = colInfo[c.name];
            return (
              <tr key={c.name} className="border-t border-line">
                <td className="px-5 py-2.5 font-medium">{c.name}<div className="text-[11.5px] font-normal text-muted">col {c.letter} · {c.stats?.filled?.toLocaleString()} filled</div></td>
                <td className="px-3"><Badge>{c.dtype}</Badge></td>
                <td className="max-w-[260px] px-3 text-[12px] text-ink-2"><div className="truncate">{(c.stats?.top || []).slice(0, 4).map((x: any) => x[0]).join(" · ")}</div></td>
                <td className="px-3">
                  <Select value={map[c.name] || ""} onChange={(e) => setMap((m) => ({ ...m, [c.name]: e.target.value }))} className={cx("w-56", map[c.name] && "border-primary/50")}>
                    <option value="">— not used —</option>
                    {onto.roles.map((r: any) => <option key={r.key} value={r.key}>{r.label}</option>)}
                  </Select>
                </td>
                <td className="px-5 text-[12px]">
                  {info?.role ? <span className="mr-2 inline-flex items-center gap-1 font-medium"><Brain className="size-3.5 text-primary" />{Math.round(info.confidence * 100)}%</span> : null}
                  <span className="text-muted">{(info?.alternatives || []).filter((a: any) => a.role !== info?.role).slice(0, 2).map((a: any) => `${a.role.replace(/_/g, " ")} ${Math.round(a.p * 100)}%`).join(" · ")}</span>
                </td>
              </tr>);
          })}</tbody></table></div>
      </Card>
    </div>
  );
}

// ------------------------------------------------------------------ quality
function Quality({ t, onShowRows }: { t: any; onShowRows: (rows: number[]) => void }) {
  const q = t.quality;
  if (!q) return <Card><Empty title="Quality checks run on order books and job-work ledgers" /></Card>;
  return (
    <div className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-3">
        <div className="card p-4"><div className="text-[12.5px] text-muted">Quality score</div><div className={cx("text-[28px] font-semibold tabular", q.score >= 95 ? "text-good" : q.score >= 80 ? "text-warning" : "text-critical")}>{q.score}</div></div>
        <div className="card p-4"><div className="text-[12.5px] text-muted">Rows checked</div><div className="text-[28px] font-semibold tabular">{q.rows.toLocaleString()}</div></div>
        <div className="card p-4"><div className="text-[12.5px] text-muted">Rules triggered</div><div className="text-[28px] font-semibold tabular">{q.issues.length}</div></div>
      </div>
      <Card title="Findings" subtitle="Validation rules applied by the data pipeline">
        {q.issues.length === 0 ? <Empty icon={<ShieldCheck className="size-6" />} title="No issues found" /> : (
          <div className="divide-y divide-line">
            {q.issues.map((i: any) => (
              <div key={i.rule} className="flex flex-wrap items-center gap-3 py-3">
                <Badge tone={i.severity === "error" ? "critical" : i.severity === "warning" ? "warning" : "info"}>{i.severity}</Badge>
                <div className="min-w-0 flex-1"><div className="font-medium">{i.message}</div><div className="text-[12px] text-muted">{i.rule} · rows {i.sample_rows.slice(0, 8).join(", ")}{i.count > 8 ? "…" : ""}</div></div>
                <span className="font-semibold tabular">{i.count.toLocaleString()}</span>
                <Button size="sm" onClick={() => onShowRows(i.sample_rows)}>Show rows</Button>
              </div>))}
          </div>)}
      </Card>
    </div>
  );
}

// ------------------------------------------------------------------ form template
function Template({ t }: { t: any }) {
  const f = t.form || {};
  const cells: [number, number, any][] = f.cells || [];
  const maxR = Math.min(70, Math.max(0, ...cells.map((c) => c[0])) + 1);
  const maxC = Math.max(0, ...cells.map((c) => c[1])) + 1;
  const grid = new Map(cells.map(([r, c, v]) => [`${r}:${c}`, v]));
  return (
    <div className="grid gap-4 xl:grid-cols-[1fr_320px]">
      <Card title="Template layout" subtitle="Print template detected in this sheet (first 70 rows)" bodyClass="overflow-auto">
        <table className="border-collapse text-[11.5px]"><tbody>
          {Array.from({ length: maxR }, (_, r) => (
            <tr key={r}>{Array.from({ length: maxC }, (_, c) => <td key={c} className="h-6 min-w-[70px] border border-line px-1.5 text-ink-2">{cellText(grid.get(`${r}:${c}`))}</td>)}</tr>))}
        </tbody></table>
      </Card>
      <Card title="Extracted information" subtitle="Used for printed documents (editable in Settings)">
        <dl className="space-y-2.5 text-[13px]">
          {f.title && <div><dt className="text-muted">Document title</dt><dd className="font-medium">{f.title}</dd></div>}
          {f.company?.name && <div><dt className="text-muted">Company</dt><dd className="font-medium">{f.company.name}</dd></div>}
          {f.company?.address?.length > 0 && <div><dt className="text-muted">Address</dt><dd>{f.company.address.join(", ")}</dd></div>}
          {f.company?.gstin && <div><dt className="text-muted">GSTIN</dt><dd className="tabular">{f.company.gstin}</dd></div>}
          {f.copies?.length > 0 && <div><dt className="text-muted">Copies</dt><dd>{f.copies.join(" · ")}</dd></div>}
          {f.tariff_code && <div><dt className="text-muted">Tariff / SAC</dt><dd className="tabular">{f.tariff_code}</dd></div>}
          {f.labels?.length > 0 && <div><dt className="text-muted">Field labels</dt><dd className="text-ink-2">{f.labels.join(", ")}</dd></div>}
        </dl>
      </Card>
    </div>
  );
}
